#! /bin/sh

set -e

install-info --quiet --section "General commands" "General commands" \
 /usr/info/find.info.gz

# In older releases, /var/lib/locate was owned by nobody
# findutils_4.1-12 installed /var/lib/locate as root:root
chown root:root /var/lib/locate
chmod 755 /var/lib/locate

# In some releases, updatedb.conf was installed executable
if [ -x /etc/updatedb.conf ]; then
  chmod 644 /etc/updatedb.conf
fi
