#! /bin/sh

set -e

install-info --quiet --section "General commands" "General commands" \
 /usr/info/find.info.gz

# findutils_4.1-12 installed /var/lib/locate as root:root
chown root:root /var/lib/locate
chmod 755 /var/lib/locate
